Add block after list of comments on news page
AlinaMoskieva/sport_cms pull request #36
Opened 2016-09-28 16:40 UTC by AlinaMoskieva

please review, @VladislavNikoshnov )

2016-09-29 08:23 UTC, VladislavNikoshnov requested changes

2016-09-29 08:23 UTC, VladislavNikoshnov commented on app/assets/javascripts/page.js.coffee
> +class Page
а теперь слабо сделать тоже самое, но только с помощью CSS?

2016-09-29 08:23 UTC, VladislavNikoshnov commented on app/decorators/page_decorator.rb
> +  def hours
название метода мало о чем говорит

2016-09-29 08:26 UTC, AlinaMoskieva commented on app/assets/javascripts/page.js.coffee
> +class Page
сейчас попробую )

2016-10-04 15:51 UTC, VladislavNikoshnov approved these changes
в целом 🆗

2016-10-04 16:09 UTC, merged