WIP: As a user I can like page and comments
AlinaMoskieva/sport_cms pull request #39
Opened 2016-10-04 16:10 UTC by AlinaMoskieva

2016-10-11 23:01 UTC, VladislavNikoshnov requested changes

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/controllers/likes_controller.rb
> +class LikesController < ApplicationController
а этот контроллер для чего используется?

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/decorators/application_decorator.rb
> +  def like?(user)
попробуй найти более подходящее место для этого

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/models/like.rb
> +  validates :likeable_id, :likeable_type, :user, presence: true
а мб просто `:likeable`?

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
> +      .medium-4.columns
```
- if policy(page).like?
  .medium-4.columns
    .page-like-box
      .like-box
        ...
```

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
> +      .medium-4.columns
попробуем так?

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
>              = "Viewed #{page.visitors} times"
не надо так

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
>          - if current_user.present?
а можешь использовать альтернативный метод?

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
>            - if policy(page).owner?
`if policy(page).owner?` серьезно?
Название метода совершенно ничего не говорит

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
>              = (link_to "Edit page", edit_page_path(page), class: "small secondary button")
для чего тут скобки?

2016-10-11 23:01 UTC, VladislavNikoshnov commented on app/views/pages/show.html.slim
>              = link_to("Subscribe", page_subscriptions_path(page), method: :post, class: "small secondary button")
вынести в декоратор

2016-10-14 15:24 UTC, AlinaMoskieva commented on app/views/pages/show.html.slim
>              = "Viewed #{page.visitors} times"
ты про page.likes_count ? )

2017-12-11 13:34 UTC, AlinaMoskieva commented
@VladislavNikoshnov review please )

2025-04-07 08:25 UTC, closed without merging