As user I can subscribe on content
AlinaMoskieva/sport_cms pull request #40
Opened 2016-10-11 17:06 UTC by AlinaMoskieva

please review, @VladislavNikoshnov )

2016-10-11 22:43 UTC, VladislavNikoshnov requested changes
app/assets/stylesheets/views/subscribe-block.scss

какой то ненужный файл

2016-10-11 22:43 UTC, VladislavNikoshnov commented on app/assets/javascripts/subscriptions.js.coffee
> +    @subscribe_button = $(".subscribe-button", @$el)
в JavaScript используется другой подход к именованию переменных и функций в отличии от Ruby. Попробуй найти стайлгайды и исправить стилевое оформление кода

2016-10-11 22:43 UTC, VladislavNikoshnov commented on app/assets/javascripts/subscriptions.js.coffee
> +        @unsubscribe_button.show()
Слабо сделать hide() show() для кнопок используя CSS и используя только переключение одного класса в JavaScript

2016-10-11 22:43 UTC, VladislavNikoshnov commented on app/controllers/pages/subscriptions_controller.rb
>      expose(:subscriptions)
не совсем уверен, но можем ли мы, добавить связь `subscriptions` в модель `Page`, а в данном месте добавить параметр `ancestor:`

2016-10-11 22:43 UTC, VladislavNikoshnov commented on app/decorators/page_decorator.rb
> +  def subscription_block(user)
придумай более подходящее название

2017-12-11 13:41 UTC, AlinaMoskieva commented
@VladislavNikoshnov review please )

2025-04-07 08:26 UTC, closed without merging